### ISSUE TITLE
`generate_daemon_image` script does not work

### ISSUE THREAD

**Issue by michaelsevilla** [ivotron/docker-cephdev#37]
This line [here](https://github.com/systemslab/docker-cephdev/blob/master/builder-base/scripts/generate_daemon_image#L49) was breaking my automated build. Changing it to this works:

```c++
ceph/daemon:jewel -c "cp -r $CEPH_INSTALL_PATH/* / || true && cp /root/bin/singlenode /usr/bin/ || true"
```

I'm not sure why this works or why it broke. Do you have any ideas?

**Comment by ivotron** [comment]
I removed the `singlenode` script. I just copied that from the `ceph/demo` image, but I guess anybody wanting to use that should get directly from that repo
